# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build
WORKDIR /app
# Install all dependencies and build
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts
COPY src ./src
RUN npm run build
# Copy full node_modules for runtime

FROM node:lts-alpine
WORKDIR /app
# Copy built code
COPY --from=build /app/build ./build
# Copy dependencies
COPY --from=build /app/node_modules ./node_modules
# Copy package.json if needed
COPY package.json ./
# Default transport
ENV TRANSPORT_MODE=stdio
ENTRYPOINT ["node", "build/index.js"]
